name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install dotnet TagToVersion tool
        run: dotnet tool install -g dotnetCampus.TagToVersion

      - name: Set tag to version
        run: dotnet TagToVersion -t ${{ github.ref }}

      - name: Pack
        run: dotnet pack -c Release -p:GeneratePackageOnBuild=false -o .

      - name: Push to NuGet
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json